name: Deploy to Firebase

on:
  push:
    branches:
      - firebase/automation

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.180.1
        with:
          ruby-version: '3.3.3'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Run lane deploy_to_firebase
        run: bundle exec fastlane deploy_to_firebase