name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.180.1
        with:
          ruby-version: '3.3.4'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run lane deploy_to_firebase
        run: bundle exec fastlane deploy_to_firebase