  name: Deploy to Firebase

  on:
    push:
      branches:
        - firebase/automation

  jobs:
    deploy:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v4.1.7

        - name: Setup Ruby
          uses: ruby/setup-ruby@v1.180.1
          with:
            ruby-version: '3.3.3'

        - name: Install dependencies
          run: |
            gem install bundler
            bundle install

        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'

        - name: Make gradlew executable
          run: chmod +x gradlew

        - name: Build project
          run: ./gradlew build

        - name: Install Firebase CLI
          run: npm install -g firebase-tools

        - name: Deploy to Firebase
          run: firebase deploy --only hosting
          env:
            FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
